import { Episode, PricingPlan, Travel, User } from '../models/travel.models';

const images = {
  baliHero:
    'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1800&q=85',
  baliBeach:
    'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=85',
  baliRice:
    'https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=1200&q=85',
  kyrgyzHero:
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=85',
  kyrgyzCamp:
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85',
  italyHero:
    'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1800&q=85',
  italyStreet:
    'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?auto=format&fit=crop&w=1200&q=85',
  thailandHero:
    'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1800&q=85',
  thailandIsland:
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85',
  japanHero:
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1800&q=85',
  japanNight:
    'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=85',
  avatar: '/sebastien-tricard.jpg',
};

export const mockUser: User = {
  id: 'user-1',
  name: 'Sebastien Tricard',
  avatarUrl: images.avatar,
  plan: 'Premium Voyage',
  totalPhotos: 1284,
  totalEpisodes: 10,
};

export const mockEpisodes: Episode[] = [
  {
    id: '1',
    travelId: 'bali-2025',
    seasonNumber: 1,
    episodeNumber: 1,
    title: "L'arrivee a Bali",
    subtitle: 'Les premieres lumieres de l ile',
    summary:
      "Le voyage commence dans l humidite douce de Denpasar, entre les scooters, les offrandes posees devant les portes et la premiere route vers Ubud. Les photos disperses deviennent un prologue fluide: les valises encore ouvertes, un rire dans le taxi, puis la sensation de comprendre que l aventure vient vraiment de commencer.",
    duration: '18 min',
    location: 'Denpasar, Ubud',
    date: '12 mai 2025',
    photoCount: 127,
    coverImage: images.baliHero,
    videoStill: images.baliBeach,
    progress: 62,
    remaining: '7 min restantes',
    scenes: [
      {
        id: 'scene-1',
        title: 'Arrivee',
        timecode: '00:00',
        description: "Sortie de l aeroport, chaleur immediate, premiere image du voyage.",
        imageUrl: images.baliHero,
      },
      {
        id: 'scene-2',
        title: 'Decouverte',
        timecode: '03:20',
        description: 'Les rues de Denpasar defilent comme une introduction de serie.',
        imageUrl: images.baliBeach,
      },
      {
        id: 'scene-3',
        title: 'Premiere randonnee',
        timecode: '07:10',
        description: 'Les rizieres d Ubud donnent au recit son premier grand plan.',
        imageUrl: images.baliRice,
      },
      {
        id: 'scene-4',
        title: 'Rencontre locale',
        timecode: '11:40',
        description: 'Une conversation avec un guide transforme les photos en souvenir vivant.',
        imageUrl: images.baliRice,
      },
      {
        id: 'scene-5',
        title: 'Coucher de soleil',
        timecode: '15:05',
        description: 'La plage devient le generique de fin du premier episode.',
        imageUrl: images.baliBeach,
      },
    ],
  },
  {
    id: '2',
    travelId: 'bali-2025',
    seasonNumber: 1,
    episodeNumber: 2,
    title: 'Rizieres et temples',
    subtitle: 'Une journee entre silence et vertige',
    summary:
      'Les marches d Ubud, les temples caches et les terrasses de riz composent une journee plus lente, presque cinematographique, ou chaque photo retrouve sa place dans le rythme du voyage.',
    duration: '22 min',
    location: 'Ubud',
    date: '14 mai 2025',
    photoCount: 186,
    coverImage: images.baliRice,
    videoStill: images.baliRice,
    progress: 0,
    remaining: '22 min restantes',
    scenes: [
      {
        id: 'scene-6',
        title: 'Le sentier des rizieres',
        timecode: '02:05',
        description: 'La camera traverse la brume et retrouve les meilleurs panoramas.',
        imageUrl: images.baliRice,
      },
      {
        id: 'scene-7',
        title: 'Temple au bord de l eau',
        timecode: '13:50',
        description: 'Les details des offrandes donnent une respiration au montage.',
        imageUrl: images.baliHero,
      },
    ],
  },
  {
    id: '3',
    travelId: 'bali-2025',
    seasonNumber: 1,
    episodeNumber: 3,
    title: 'La nuit de Canggu',
    subtitle: 'Surf, pluie chaude et derniers messages',
    summary:
      'La saison prend de la vitesse avec les cafes de Canggu, une session de surf improvisee et une pluie tropicale qui transforme les photos floues en scene finale.',
    duration: '16 min',
    location: 'Canggu',
    date: '18 mai 2025',
    photoCount: 142,
    coverImage: images.baliBeach,
    videoStill: images.baliBeach,
    progress: 0,
    remaining: '16 min restantes',
    scenes: [
      {
        id: 'scene-8',
        title: 'Session au large',
        timecode: '04:15',
        description: 'Les vagues deviennent une sequence nerveuse et lumineuse.',
        imageUrl: images.baliBeach,
      },
      {
        id: 'scene-9',
        title: 'Pluie sur Canggu',
        timecode: '12:30',
        description: 'Les neons et les rires ferment la premiere saison.',
        imageUrl: images.baliBeach,
      },
    ],
  },
  {
    id: '4',
    travelId: 'kyrgyzstan-2025',
    seasonNumber: 1,
    episodeNumber: 1,
    title: 'La route vers Song-Kul',
    subtitle: 'Quand la montagne impose son rythme',
    summary:
      'Le trajet quitte la ville pour les pistes hautes du Kirghizistan. Les virages, les chevaux et le vent deviennent le fil rouge d un episode plus brut, construit autour de la sensation d etre loin.',
    duration: '24 min',
    location: 'Lac Song-Kul',
    date: '2 juillet 2025',
    photoCount: 211,
    coverImage: images.kyrgyzHero,
    videoStill: images.kyrgyzCamp,
    progress: 20,
    remaining: '19 min restantes',
    scenes: [
      {
        id: 'scene-10',
        title: 'Depart de Bichkek',
        timecode: '01:10',
        description: 'La ville disparait dans le retroviseur avant les grands plateaux.',
        imageUrl: images.kyrgyzCamp,
      },
      {
        id: 'scene-11',
        title: 'Nuit en yourte',
        timecode: '17:45',
        description: 'Le froid, les etoiles et le silence deviennent le coeur du recit.',
        imageUrl: images.kyrgyzHero,
      },
    ],
  },
  {
    id: '5',
    travelId: 'kyrgyzstan-2025',
    seasonNumber: 1,
    episodeNumber: 2,
    title: 'Chevaux dans la vallee',
    subtitle: 'Une journee avec les nomades',
    summary:
      'Les images de chevaux, de the chaud et de routes de terre sont assemblees comme un carnet de terrain, avec une narration calme et tres humaine.',
    duration: '19 min',
    location: 'Naryn',
    date: '4 juillet 2025',
    photoCount: 173,
    coverImage: images.kyrgyzCamp,
    videoStill: images.kyrgyzHero,
    progress: 0,
    remaining: '19 min restantes',
    scenes: [
      {
        id: 'scene-12',
        title: 'Depart a cheval',
        timecode: '03:25',
        description: 'Le montage ralentit pour laisser respirer le paysage.',
        imageUrl: images.kyrgyzHero,
      },
      {
        id: 'scene-13',
        title: 'Le diner partage',
        timecode: '14:00',
        description: 'Les portraits familiaux deviennent une scene de transmission.',
        imageUrl: images.kyrgyzCamp,
      },
    ],
  },
  {
    id: '6',
    travelId: 'italy-2024',
    seasonNumber: 1,
    episodeNumber: 1,
    title: 'Venise au petit matin',
    subtitle: 'La ville avant la foule',
    summary:
      'La saison italienne s ouvre sur les canaux silencieux, les volets encore fermes et les premieres barques. Les souvenirs prennent une texture de film ancien sans perdre leur naturel.',
    duration: '17 min',
    location: 'Venise',
    date: '21 septembre 2024',
    photoCount: 154,
    coverImage: images.italyHero,
    videoStill: images.italyStreet,
    progress: 100,
    remaining: 'Episode termine',
    scenes: [
      {
        id: 'scene-14',
        title: 'Canal vide',
        timecode: '02:00',
        description: 'La lumiere pale transforme les premieres photos en ouverture.',
        imageUrl: images.italyHero,
      },
      {
        id: 'scene-15',
        title: 'Cafe debout',
        timecode: '09:45',
        description: 'Une pause minuscule devient un souvenir central.',
        imageUrl: images.italyStreet,
      },
    ],
  },
  {
    id: '7',
    travelId: 'italy-2024',
    seasonNumber: 1,
    episodeNumber: 2,
    title: 'Rome, le soir',
    subtitle: 'Piazzas, fontaines et conversations longues',
    summary:
      'Rome prend la forme d une promenade nocturne, avec les photos de groupe, les assiettes partagees et les monuments qui apparaissent au coin des rues.',
    duration: '21 min',
    location: 'Rome',
    date: '26 septembre 2024',
    photoCount: 199,
    coverImage: images.italyStreet,
    videoStill: images.italyStreet,
    progress: 35,
    remaining: '14 min restantes',
    scenes: [
      {
        id: 'scene-16',
        title: 'Derniere piazza',
        timecode: '16:30',
        description: 'Les photos de nuit deviennent un final doux et collectif.',
        imageUrl: images.italyStreet,
      },
    ],
  },
  {
    id: '8',
    travelId: 'thailand-2024',
    seasonNumber: 1,
    episodeNumber: 1,
    title: 'Bangkok en acceleration',
    subtitle: 'Tuk-tuks, marches et premiere nuit',
    summary:
      'Bangkok est montee comme un episode rapide: sons de rue, temples dores, food court et chaleur de fin de jour. L IA garde le chaos mais retrouve une ligne narrative claire.',
    duration: '20 min',
    location: 'Bangkok',
    date: '8 fevrier 2024',
    photoCount: 230,
    coverImage: images.thailandHero,
    videoStill: images.thailandHero,
    progress: 0,
    remaining: '20 min restantes',
    scenes: [
      {
        id: 'scene-17',
        title: 'Marche de nuit',
        timecode: '05:10',
        description: 'Les enseignes et les plats deviennent une scene sensorielle.',
        imageUrl: images.thailandHero,
      },
      {
        id: 'scene-18',
        title: 'Temple dore',
        timecode: '12:55',
        description: 'Le recit ralentit autour des gestes et des details.',
        imageUrl: images.thailandHero,
      },
    ],
  },
  {
    id: '9',
    travelId: 'thailand-2024',
    seasonNumber: 1,
    episodeNumber: 2,
    title: 'Iles du Sud',
    subtitle: 'Un episode presque silencieux',
    summary:
      'Les bateaux longs, l eau turquoise et les photos prises au hasard composent un chapitre contemplatif, parfait pour montrer la puissance emotionnelle du produit.',
    duration: '15 min',
    location: 'Krabi',
    date: '13 fevrier 2024',
    photoCount: 168,
    coverImage: images.thailandIsland,
    videoStill: images.thailandIsland,
    progress: 0,
    remaining: '15 min restantes',
    scenes: [
      {
        id: 'scene-19',
        title: 'Baie turquoise',
        timecode: '07:20',
        description: 'Une sequence courte transforme les paysages en respiration.',
        imageUrl: images.thailandIsland,
      },
    ],
  },
  {
    id: '10',
    travelId: 'japan-2023',
    seasonNumber: 1,
    episodeNumber: 1,
    title: 'Kyoto sous la pluie',
    subtitle: 'Lanternes, trains et temples rouges',
    summary:
      'Le Japon revient comme une saison archivee: torii rouges, parapluies transparents, ramen tardif et rues calmes. Les souvenirs anciens sont reconstruits avec une precision nouvelle.',
    duration: '23 min',
    location: 'Kyoto',
    date: '3 novembre 2023',
    photoCount: 244,
    coverImage: images.japanHero,
    videoStill: images.japanNight,
    progress: 75,
    remaining: '6 min restantes',
    scenes: [
      {
        id: 'scene-20',
        title: 'Lanternes apres la pluie',
        timecode: '18:20',
        description: 'Le dernier acte transforme les images nocturnes en souvenir intact.',
        imageUrl: images.japanNight,
      },
    ],
  },
];

export const mockTravels: Travel[] = [
  {
    id: 'bali-2025',
    title: 'Bali 2025',
    destination: 'Bali',
    country: 'Indonesie',
    year: 2025,
    tagline: 'Rizieres, plages et temples au rythme d une premiere grande saison.',
    description:
      'Une serie solaire qui transforme les photos d Ubud, Canggu et Denpasar en recit de voyage premium.',
    coverImage: images.baliBeach,
    heroImage: images.baliHero,
    posterImage: images.baliRice,
    duration: '56 min',
    episodeCount: 3,
    photoCount: 455,
    progress: 62,
    remaining: '7 min restantes',
    featured: true,
    moodTags: ['Cinematographique', 'Emotionnel', 'Aventure'],
    episodes: mockEpisodes.filter((episode) => episode.travelId === 'bali-2025'),
  },
  {
    id: 'kyrgyzstan-2025',
    title: 'Kirghizistan 2025',
    destination: 'Song-Kul',
    country: 'Kirghizistan',
    year: 2025,
    tagline: 'Une traversee nomade entre pistes, yourtes et grands plateaux.',
    description:
      'Un voyage plus brut et humain, ideal pour montrer la reconstruction narrative de souvenirs disperses.',
    coverImage: images.kyrgyzHero,
    heroImage: images.kyrgyzHero,
    posterImage: images.kyrgyzCamp,
    duration: '43 min',
    episodeCount: 2,
    photoCount: 384,
    progress: 20,
    remaining: '19 min restantes',
    featured: false,
    moodTags: ['Documentaire', 'Inspirant', 'Nostalgique'],
    episodes: mockEpisodes.filter((episode) => episode.travelId === 'kyrgyzstan-2025'),
  },
  {
    id: 'italy-2024',
    title: 'Italie 2024',
    destination: 'Venise et Rome',
    country: 'Italie',
    year: 2024,
    tagline: 'Canaux silencieux, diners tardifs et villes qui ressemblent a du cinema.',
    description:
      'Une saison europeenne elegante, entre architecture, nourriture et conversations qui durent.',
    coverImage: images.italyHero,
    heroImage: images.italyHero,
    posterImage: images.italyStreet,
    duration: '38 min',
    episodeCount: 2,
    photoCount: 353,
    progress: 68,
    remaining: '14 min restantes',
    featured: false,
    moodTags: ['Nostalgique', 'Culture', 'Couple'],
    episodes: mockEpisodes.filter((episode) => episode.travelId === 'italy-2024'),
  },
  {
    id: 'thailand-2024',
    title: 'Thailande 2024',
    destination: 'Bangkok et Krabi',
    country: 'Thailande',
    year: 2024,
    tagline: 'Un contraste vif entre energie urbaine et iles presque silencieuses.',
    description:
      'Une saison tres visuelle, parfaite pour alterner scenes rapides et pauses contemplatives.',
    coverImage: images.thailandHero,
    heroImage: images.thailandHero,
    posterImage: images.thailandIsland,
    duration: '35 min',
    episodeCount: 2,
    photoCount: 398,
    progress: 0,
    remaining: '35 min restantes',
    featured: false,
    moodTags: ['Fun', 'Activites', 'Paysages'],
    episodes: mockEpisodes.filter((episode) => episode.travelId === 'thailand-2024'),
  },
  {
    id: 'japan-2023',
    title: 'Japon 2023',
    destination: 'Kyoto',
    country: 'Japon',
    year: 2023,
    tagline: 'Une archive de voyage transformee en episode intime et precis.',
    description:
      'La preuve que Never Forget your Trip peut redonner une forme forte a un voyage deja ancien dans la galerie photo.',
    coverImage: images.japanHero,
    heroImage: images.japanHero,
    posterImage: images.japanNight,
    duration: '23 min',
    episodeCount: 1,
    photoCount: 244,
    progress: 75,
    remaining: '6 min restantes',
    featured: false,
    moodTags: ['Cinematographique', 'Culture', 'Nuit'],
    episodes: mockEpisodes.filter((episode) => episode.travelId === 'japan-2023'),
  },
];

export const mockPricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'Gratuit',
    price: '0 EUR',
    cadence: 'pour commencer',
    description: 'Un episode offert pour transformer un premier souvenir en demo concrete.',
    features: ['1 episode offert', 'Import photo simule', 'Qualite teaser', 'Partage prive'],
  },
  {
    id: 'premium-voyage',
    name: 'Premium Voyage',
    price: '4.99 EUR',
    cadence: 'par voyage',
    description: 'La formule ideale pour generer une saison complete apres un grand depart.',
    features: ['Voyage complet', 'Jusqu a 8 episodes', 'Style narratif au choix', 'Export partageable'],
    highlighted: true,
  },
  {
    id: 'premium-plus',
    name: 'Premium Plus',
    price: '9.99 EUR',
    cadence: 'par mois',
    description: 'Pour les familles et voyageurs frequents qui veulent archiver plusieurs saisons.',
    features: ['Voyages illimites', 'Episodes HD', 'Profils famille', 'Souvenirs recurrents'],
  },
  {
    id: 'organizations',
    name: 'Organisations',
    price: 'Sur devis',
    cadence: 'accompagnement',
    description: 'Une offre pensee pour les colonies, associations, EHPAD et voyages de groupe.',
    features: ['Colonies et sejours', 'Associations', 'EHPAD', 'Espace administrateur'],
    audience: 'B2B',
  },
];

export const mockScenes = mockEpisodes.flatMap((episode) => episode.scenes);
